import editAdd from "../../support/pageObject/edit.add"
import changePass from "../../support/pageObject/edit.add"
const userData = require('../../fixtures/userLogin.json')

describe('Verify Change Address Functionality', () => {
    beforeEach(() => {
        cy.visit('https://magento.softwaretestingboard.com/customer/account/login')
        cy.login('emailtestingpramesta@gmail.com', 'EmailTesting.123')
        cy.get('.logged-in').should('contain.text','Welcome')
        cy.accountMenu()
    })
   
    //Custom Command
    it('Success Edit Address', () => {
        cy.get('.firstname').clear().type('NamaDepan')
        cy.get('.lastname').clear().type('NamaBelakang')
        cy.get('.company').clear().type('Sanbercode')
        cy.get('.telephone').clear().type('081234566789')
        cy.get('.street_1').clear().type('Jl. Kemerderkaan')
        cy.get('.street_2').clear().type('Indonesia')
        cy.get('.street_3').clear().type('Jawa Barat')
        cy.get('.city').clear().type('Indiana')
        cy.get('.region').clear().type('Jakarta')
        cy.get('.zip').clear().type('61526')
        cy.get('.country').clear().type('Indonesia')
        cy.get('#Save Address').click()
        cy.get(editAdd.message-success).should('be.visible')
    })
    it('Success Edit Address_Required only', () => {
        cy.get('.firstname').clear().type('NamaDepan')
        cy.get('.lastname').clear().type('NamaBelakang')
        cy.get('.telephone').clear().type('081234566789')
        cy.get('.street_1').clear().type('Jl. Kemerderkaan')
        cy.get('.city').clear().type('Indiana')
        cy.get('.zip').clear().type('61526')
        cy.get('.country').clear().type('Indonesia')
        cy.get('#Save Address').click()
        cy.get(editAdd.message-success).should('be.visible')
    })
    it('Failed Update_Firstname not Field', () => {
        cy.get('.firstname').clear()
        cy.get('.lastname').clear().type('NamaBelakang')
        cy.get('.company').clear().type('Sanbercode')
        cy.get('.telephone').clear().type('081234566789')
        cy.get('.street_1').clear().type('Jl. Kemerderkaan')
        cy.get('.street_2').clear().type('Indonesia')
        cy.get('.street_3').clear().type('Jawa Barat')
        cy.get('.city').clear().type('Indiana')
        cy.get('.region').clear().type('Jakarta')
        cy.get('.zip').clear().type('61526')
        cy.get('.country').clear().type('Indonesia')
        cy.get('#Save Address').click()
        //cy.get(#firstname-error).should('be.visible')
    })
    it('Failed Update_Lastname not Field', () => {
        cy.get('.firstname').clear('NamaDepan')
        cy.get('.lastname').clear().type('')
        cy.get('.company').clear().type('Sanbercode')
        cy.get('.telephone').clear().type('081234566789')
        cy.get('.street_1').clear().type('Jl. Kemerderkaan')
        cy.get('.street_2').clear().type('Indonesia')
        cy.get('.street_3').clear().type('Jawa Barat')
        cy.get('.city').clear().type('Indiana')
        cy.get('.region').clear().type('Jakarta')
        cy.get('.zip').clear().type('61526')
        cy.get('.country').clear().type('Indonesia')
        cy.get('#Save Address').click()
        //cy.get(#lastname-error).should('be.visible')
    })
    it('Failed Update_City not Field', () => {
        cy.get('.firstname').clear('NamaDepan')
        cy.get('.lastname').clear().type('NamaBelakang')
        cy.get('.company').clear().type('Sanbercode')
        cy.get('.telephone').clear().type('081234566789')
        cy.get('.street_1').clear().type('Jl. Kemerderkaan')
        cy.get('.street_2').clear().type('Indonesia')
        cy.get('.street_3').clear().type('Jawa Barat')
        cy.get('.city').clear().type('')
        cy.get('.region').clear().type('Jakarta')
        cy.get('.zip').clear().type('61526')
        cy.get('.country').clear().type('Indonesia')
        cy.get('#Save Address').click()
        //cy.get(#city-error).should('be.visible')
    })

})